name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.8"
            torch: "1.11.0"
            torchvision: "0.12.0"
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Test
      run: |
        pip install torch==${{ matrix.torch }} torchvision==${{ matrix.torchvision }} -f https://download.pytorch.org/whl/torch_stable.html
        pip install coverage pytest
        coverage run
        coverage xml && coverage report -m
    - uses: codecov/codecov-action@main
