model = dict(
    multilabel_classifier=dict(
        type='Classifier',
        pretrained='data/coco/prompt/prompt1.pth',
        in_features=2048,
        out_features=80,
        split='COCO',
    ),
    multilabel_loss=dict(
        type='AsymmetricLoss',
        weight=dict(
            type='WarmupScheduler',
            value=16,
            iter_=1000,
        ),
        gamma_neg=4,
        gamma_pos=0,
        clip=0.05,
        disable_torch_grad_focal_loss=True,
    ),
)
